const { toMermaidMarkdown } = require("./export-mermaid");

function toHtmlDocumentation(model, title = "OrgScript Documentation", options = {}) {
  const sections = model.body.map((node) => renderNode(node, options)).filter(Boolean);

  const toc = model.body
    .map((node) => {
      const label = `${toKindLabel(node.type)}: ${node.name}`;
      const id = toAnchor(node);
      return `<li><a href="#${id}">${escapeHtml(label)}</a></li>`;
    })
    .join("\n");

  const html = `<!DOCTYPE html>
<html lang="${escapeHtml(resolveHtmlLanguage(model))}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(title)}</title>
  <style>
    :root {
      --primary: #2563eb;
      --bg: #f8fafc;
      --text: #1e293b;
      --border: #e2e8f0;
      --card-bg: #ffffff;
    }
    body {
      font-family: 'Inter', system-ui, -apple-system, sans-serif;
      line-height: 1.6;
      color: var(--text);
      background: var(--bg);
      margin: 0;
      padding: 2rem;
      max-width: 1000px;
      margin: 0 auto;
    }
    header {
      margin-bottom: 3rem;
      border-bottom: 2px solid var(--border);
      padding-bottom: 1rem;
    }
    nav {
      background: var(--card-bg);
      padding: 1.5rem;
      border-radius: 8px;
      box-shadow: 0 1px 3px rgba(0,0,0,0.1);
      margin-bottom: 3rem;
    }
    nav ul {
      list-style: none;
      padding: 0;
      columns: 2;
    }
    nav a {
      color: var(--primary);
      text-decoration: none;
    }
    nav a:hover {
      text-decoration: underline;
    }
    section {
      background: var(--card-bg);
      padding: 2rem;
      border-radius: 8px;
      box-shadow: 0 1px 3px rgba(0,0,0,0.1);
      margin-bottom: 2rem;
      scroll-margin-top: 2rem;
    }
    h1, h2, h3 {
      color: #0f172a;
    }
    .kind {
      display: inline-block;
      text-transform: uppercase;
      font-size: 0.75rem;
      font-weight: 700;
      letter-spacing: 0.05em;
      color: #64748b;
      margin-bottom: 0.5rem;
    }
    .mermaid {
      background: #fff;
      padding: 1rem;
      border: 1px solid var(--border);
      border-radius: 4px;
      margin: 1.5rem 0;
      overflow-x: auto;
    }
    footer {
      margin-top: 4rem;
      text-align: center;
      color: #94a3b8;
      font-size: 0.875rem;
    }
    pre {
      background: #f1f5f9;
      padding: 1rem;
      border-radius: 4px;
      font-size: 0.875rem;
    }
    code {
      font-family: 'Fira Code', 'Cascadia Code', monospace;
      background: #f1f5f9;
      padding: 0.2em 0.4em;
      border-radius: 4px;
    }
    ul {
      padding-left: 1.5rem;
    }
  </style>
</head>
<body>
  <header>
    <h1>${escapeHtml(title)}</h1>
    <p>Generated by OrgScript</p>
    ${renderDocumentMetadata(model, options)}
  </header>

  <nav>
    <h2>Table of Contents</h2>
    <ul>
      ${toc}
    </ul>
  </nav>

  <main>
    ${sections.join("\n")}
  </main>

  <footer>
    <p>OrgScript - Human-readable, AI-interpretable business logic.</p>
  </footer>

  <script type="module">
    import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs';
    mermaid.initialize({ startOnLoad: true, theme: 'default' });
  </script>
</body>
</html>`;

  return html;
}

function renderNode(node, options) {
  const id = toAnchor(node);
  const kind = toKindLabel(node.type);
  const mermaid = getMermaidForNode(node);

  return `
    <section id="${id}">
      <span class="kind">${escapeHtml(kind)}</span>
      <h2>${escapeHtml(node.name)}</h2>
      <div class="summary-container">
        ${renderSummary(node, options)}
      </div>
      ${mermaid ? `<div class="visual-container"><h3>Diagram</h3><pre class="mermaid">${escapeHtml(mermaid)}</pre></div>` : ""}
    </section>
  `;
}

function getMermaidForNode(node) {
  if (node.type !== "process" && node.type !== "stateflow") return null;
  const full = toMermaidMarkdown({ body: [node] });
  const match = full.match(/```mermaid\n([\s\S]*?)\n```/);
  return match ? match[1] : null;
}

function renderSummary(node, options = {}) {
  const metadata = renderAnnotationHtml(node, options);

  if (node.type === "role") {
    return `
      ${metadata}
      <p><strong>Permissions:</strong></p>
      <ul>${(node.can || []).map((permission) => `<li>Can perform <code>${escapeHtml(permission)}</code></li>`).join("")}</ul>
      ${(node.cannot || []).length > 0 ? `<ul>${node.cannot.map((permission) => `<li>Cannot perform <code>${escapeHtml(permission)}</code></li>`).join("")}</ul>` : ""}
    `;
  }

  if (node.type === "stateflow") {
    return `
      ${metadata}
      <p><strong>States:</strong> ${(node.states || []).map((state) => `<code>${escapeHtml(state)}</code>`).join(", ")}</p>
      <p><strong>Transitions:</strong> ${(node.transitions || []).length} paths defined.</p>
    `;
  }

  if (node.type === "rule") {
    return `
      ${metadata}
      <p><strong>Scope:</strong> Applies to <code>${escapeHtml(node.appliesTo || "universal")}</code></p>
      <p>Contains behavioral constraints and logic for <code>${escapeHtml(node.name)}</code>.</p>
    `;
  }

  if (node.type === "process") {
    const triggers = (node.body || []).filter((statement) => statement.type === "when");
    return `
      ${metadata}
      <p><strong>Triggered by:</strong> ${triggers.length > 0 ? triggers.map((trigger) => `<code>${escapeHtml(trigger.trigger)}</code>`).join(", ") : "<em>No explicit trigger</em>"}</p>
      <p>Orchestrates business logic and state transitions for the <code>${escapeHtml(node.name)}</code> process.</p>
    `;
  }

  return `${metadata}<p>Operational constraints and logic for <code>${escapeHtml(node.name)}</code>.</p>`;
}

function toAnchor(node) {
  const label = `${toKindLabel(node.type)} ${node.name}`;
  return label
    .toLowerCase()
    .replace(/ /g, "-")
    .replace(/[^a-z0-9-]/g, "");
}

function toKindLabel(type) {
  return type.replace(/([a-z])([A-Z])/g, "$1 $2").toLowerCase();
}

function escapeHtml(value) {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function renderAnnotationHtml(node, options = {}) {
  if (!options.includeAnnotations || !(node.annotations || []).length) {
    return "";
  }

  const items = node.annotations
    .map(
      (annotation) =>
        `<li><code>@${escapeHtml(annotation.key)}</code>: <code>${escapeHtml(annotation.value)}</code></li>`
    )
    .join("");

  return `<p><strong>Metadata:</strong></p><ul>${items}</ul>`;
}

function renderDocumentMetadata(model, options = {}) {
  if (!options.includeAnnotations || !model.metadata || !model.metadata.languages) {
    return "";
  }

  const items = Object.entries(model.metadata.languages)
    .map(
      ([key, value]) =>
        `<li><strong>${escapeHtml(toDocumentLanguageLabel(key))}</strong>: <code>${escapeHtml(value)}</code></li>`
    )
    .join("");

  if (!items) {
    return "";
  }

  return `<p><strong>Document metadata:</strong></p><ul>${items}</ul>`;
}

function resolveHtmlLanguage(model) {
  const languages = model.metadata ? model.metadata.languages || {} : {};
  return languages.context || languages.comments || languages.annotations || languages.source || "en";
}

function toDocumentLanguageLabel(key) {
  if (key === "source") {
    return "Source language";
  }

  if (key === "comments") {
    return "Comment language";
  }

  if (key === "annotations") {
    return "Annotation language";
  }

  if (key === "context") {
    return "Context language";
  }

  return key;
}

module.exports = { toHtmlDocumentation };
