const { toMermaidMarkdown } = require("./export-mermaid");

function toHtmlDocumentation(model, title = "OrgScript Documentation") {
  const sections = model.body
    .map((node) => renderNode(node))
    .filter(Boolean);

  const toc = model.body
    .map((node) => {
      const label = `${toKindLabel(node.type)}: ${node.name}`;
      const id = toAnchor(node);
      return `<li><a href="#${id}">${label}</a></li>`;
    })
    .join("\n");

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title}</title>
  <style>
    :root {
      --primary: #2563eb;
      --bg: #f8fafc;
      --text: #1e293b;
      --border: #e2e8f0;
      --card-bg: #ffffff;
    }
    body {
      font-family: 'Inter', system-ui, -apple-system, sans-serif;
      line-height: 1.6;
      color: var(--text);
      background: var(--bg);
      margin: 0;
      padding: 2rem;
      max-width: 1000px;
      margin: 0 auto;
    }
    header {
      margin-bottom: 3rem;
      border-bottom: 2px solid var(--border);
      padding-bottom: 1rem;
    }
    nav {
      background: var(--card-bg);
      padding: 1.5rem;
      border-radius: 8px;
      box-shadow: 0 1px 3px rgba(0,0,0,0.1);
      margin-bottom: 3rem;
    }
    nav ul {
      list-style: none;
      padding: 0;
      columns: 2;
    }
    nav a {
      color: var(--primary);
      text-decoration: none;
    }
    nav a:hover {
      text-decoration: underline;
    }
    section {
      background: var(--card-bg);
      padding: 2rem;
      border-radius: 8px;
      box-shadow: 0 1px 3px rgba(0,0,0,0.1);
      margin-bottom: 2rem;
      scroll-margin-top: 2rem;
    }
    h1, h2, h3 {
      color: #0f172a;
    }
    .kind {
      display: inline-block;
      text-transform: uppercase;
      font-size: 0.75rem;
      font-weight: 700;
      letter-spacing: 0.05em;
      color: #64748b;
      margin-bottom: 0.5rem;
    }
    .mermaid {
      background: #fff;
      padding: 1rem;
      border: 1px solid var(--border);
      border-radius: 4px;
      margin: 1.5rem 0;
      overflow-x: auto;
    }
    footer {
      margin-top: 4rem;
      text-align: center;
      color: #94a3b8;
      font-size: 0.875rem;
    }
    pre {
      background: #f1f5f9;
      padding: 1rem;
      border-radius: 4px;
      font-size: 0.875rem;
    }
    code {
      font-family: 'Fira Code', 'Cascadia Code', monospace;
      background: #f1f5f9;
      padding: 0.2em 0.4em;
      border-radius: 4px;
    }
    ul {
      padding-left: 1.5rem;
    }
    .status-bar {
      display: flex;
      gap: 1rem;
      margin-top: 1rem;
      font-size: 0.875rem;
    }
    .tag {
      background: #e2e8f0;
      padding: 0.2rem 0.6rem;
      border-radius: 999px;
    }
  </style>
</head>
<body>
  <header>
    <h1>${title}</h1>
    <p>Generated by OrgScript v0.6.0</p>
  </header>

  <nav>
    <h2>Table of Contents</h2>
    <ul>
      ${toc}
    </ul>
  </nav>

  <main>
    ${sections.join("\n")}
  </main>

  <footer>
    <p>OrgScript — Human-readable, AI-interpretable business logic.</p>
  </footer>

  <script type="module">
    import mermaid from 'https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs';
    mermaid.initialize({ startOnLoad: true, theme: 'default' });
  </script>
</body>
</html>`;

  return html;
}

function renderNode(node) {
  const id = toAnchor(node);
  const kind = toKindLabel(node.type);
  const mermaid = getMermaidForNode(node);

  return `
    <section id="${id}">
      <span class="kind">${kind}</span>
      <h2>${node.name}</h2>
      <div class="summary-container">
        ${renderSummary(node)}
      </div>
      ${mermaid ? `<div class="visual-container"><h3>Diagram</h3><pre class="mermaid">${mermaid}</pre></div>` : ""}
    </section>
  `;
}

function getMermaidForNode(node) {
  if (node.type !== "process" && node.type !== "stateflow") return null;
  const full = toMermaidMarkdown({ body: [node] });
  const match = full.match(/```mermaid\n([\s\S]*?)\n```/);
  return match ? match[1] : null;
}

function renderSummary(node) {
  if (node.type === "role") {
    return `
      <p><strong>Permissions:</strong></p>
      <ul>${(node.can || []).map(p => `<li>Can perform <code>${p}</code></li>`).join("")}</ul>
      ${(node.cannot || []).length > 0 ? `<ul>${node.cannot.map(p => `<li>Cannot perform <code>${p}</code></li>`).join("")}</ul>` : ""}
    `;
  }

  if (node.type === "stateflow") {
    return `
      <p><strong>States:</strong> ${(node.states || []).map(s => `<code>${s}</code>`).join(", ")}</p>
      <p><strong>Transitions:</strong> ${(node.transitions || []).length} paths defined.</p>
    `;
  }

  if (node.type === "rule") {
    return `
      <p><strong>Scope:</strong> Applies to <code>${node.appliesTo || "universal"}</code></p>
      <p>Contains behavioral constraints and logic for <code>${node.name}</code>.</p>
    `;
  }

  if (node.type === "process") {
    const triggers = (node.body || []).filter(s => s.type === "when");
    return `
      <p><strong>Triggered by:</strong> ${triggers.length > 0 ? triggers.map(t => `<code>${t.trigger}</code>`).join(", ") : "<em>No explicit trigger</em>"}</p>
      <p>Orchestrates business logic and state transitions for the <code>${node.name}</code> process.</p>
    `;
  }

  return `<p>Operational constraints and logic for <code>${node.name}</code>.</p>`;
}

function toAnchor(node) {
  const label = `${toKindLabel(node.type)} ${node.name}`;
  return label
    .toLowerCase()
    .replace(/ /g, "-")
    .replace(/[^a-z0-9-]/g, "");
}

function toKindLabel(type) {
  return type.replace(/([a-z])([A-Z])/g, "$1 $2").toLowerCase();
}

module.exports = { toHtmlDocumentation };
